youCanCodeAGif_en:
    cuttimes:
        - ("00:00:40.5","00:00:57.0")
        - ("00:01:00.7","00:01:04.5")
        - ("00:01:13.5","00:01:15.2")
        - ("00:01:20.3","00:01:31.5")
        - ("00:01:38.8","00:01:40.9")
        - ("00:01:47.2","00:01:48.3")
        - ("00:01:50.6","00:01:53.3")
        - ("00:01:55.9","00:02:00.0")
        - ("00:00:27.0","00:00:27.1")
    subs:
        - text: "You can't just code a gif..."
          color: 'yellow'
          pos: '830,420'
          time: '1,2.5'
        - ["Of course I can.",white,(800,420),'3,4'],
        - ["I'm going to code",white,(800,420),'4.1,7'],
        - ["this entire gif.",white,(800,480),'5.2,7'],
        - ["And I'll give you the\n source in the comments.",white,(800,450),'7.1,10'],
        - ['"You can\'t code a gif..."',white,(820,420),'11.8,13'],
        - ["It's nothing more than",white,(800,420),'14,16'],
        - ["a huge waste of time!",white,(800,480),'15,16'],
        - ["First: I download our video\nfrom Youtube.",white,(640,450),'17,19.5'],
        - ["Then I separate each scene...",white,(640,480),'20,23'],
        - ["Now I add our dialogs...",white,(640,480),'24,25.4'],
        - ["Let me see...",yellow,(640,480),'30.5,32.5'],
        - ["Can you add a bit of META?",yellow,(640,480),'32.9,34.5'],
        - ["I will put just a touch...",white,(640,420),'35,40'],
        - ["Very subtle, no one will see it.",white,(640,480),'37,40'],
        - ["Now I concatenate the scenes....",white,(640,480),'45.6,47.6'],
        - ["And to finish...",white,(640,420),'49.6,52'],
        - ["GIF THAT!",white,(640,480),'50.2,52'],
        - ["I AM",white,(640,400),'62.8,64.6'],
        - ["INVINCIBLE!!!",white,(640,460),'63.3,64.6']
youCanCodeAGif_fr:
    cuttimes:
        - ("00:00:40.5","00:00:57.0")
        - ("00:01:00.7","00:01:04.5")
        - ("00:01:13.5","00:01:15.2")
        - ("00:01:20.3","00:01:31.5")
        - ("00:01:38.8","00:01:40.9")
        - ("00:01:47.2","00:01:48.3")
        - ("00:01:50.6","00:01:53.3")
        - ("00:01:55.9","00:02:00.0")
        - ("00:00:27.0","00:00:27.1")
    subs:
        - text: "On ne peut pas\ncoder un gif..."
          color: 'yellow'
          position: '840,420'
          time: '1,2.5'
        - ["Bien sûr qu'on peut.",white,(800,420),'3,4'],
        - ["Je vais te coder",white,(800,420),'4.1,7'],
        - ["ce gif de A à Z.",white,(800,480),'5.2,7'],
        - ["Et je te mets le code\n dans les commentaires.",white,(800,450),'7.1,10'],
        - ['"On ne peut pas\ncoder un gif..."',white,(840,420),'11.8,13'],
        - ["C'est rien de plus",white,(800,420),'14,16'],
        - ["qu'une énorme perte de temps !",white,(800,480),'15,16'],
        - ["Premièrement: je télécharge la\n vidéo depuis Youtube.",white,(640,450),'17,19.5'],
        - ["Ensuite je découpe les scènes...",white,(640,480),'20,23'],
        - ["J'ajoute nos dialogues...",white,(640,480),'23.5,25.4'],
        - ["Attend voir...",yellow,(640,480),'30.3,32'],
        - ["Tu peux ajouter un peu de META ?",yellow,(640,480),'32.5,34.5'],
        - ["OK mais juste une pincée...",white,(640,420),'35,40'],
        - ["Très subtil, personne ne le verra.",white,(640,480),'37,40'],
        - ["Je colle les scènes bout à bout...",white,(640,480),'45,47'],
        - ["Et pour finir...",white,(640,420),'49.1,51.6'],
        - ["GIF MOI ÇA !",white,(640,480),'50,51.6'],
        - ["JE SUIS",white,(640,400),'62.8,64.6'],
        - ["INVINCIBLE !!!",white,(640,460),'63.3,64.6']
