def just_a_touch(subtle_level=9000):
    return """
          #####  ### #######   ######  ####### #     # #######    ###
         #     #  #  #         #     # #     # ##    # #          ###
         #        #  #         #     # #     # # #   # #          ###
         #  ####  #  #####     #     # #     # #  #  # #####       #
         #     #  #  #         #     # #     # #   # # #
         #     #  #  #         #     # #     # #    ## #          ###
          #####  ### #         ######  ####### #     # #######    ###

                              MMMMMM=
                         .MMMMMMMMMMMMMM
                       MMMMMM         MMMM
                    MMMMM              MMMMM.
              MMMMMMMM                  ?MMMM.
           .MMMMMMMM7MM                  MMMMM
           MMMMMMMMM MM                   MMMM
           MMMMMMMMM .MM                   MMM
          .MMMMMMM.   MM.M.   =MMMMMMMM.   MMM
           MMMMMMMM.MMMMMM.  MMMMMMMM MMM  MMM
           MMMMMMMMMMMM     MMMMMMMMM  MMM MMM
          MMM    MMM:  MM   MMMMMMMMM  MMM MMM
         8MM.    MMMMMMMM=  MMMMMMMM.  .M ,MM7
        MMMMMMMM..          MMMMM.     M  MMM
       .MMMMMMMMMMMMMMM       MMMMMMMMM.  MMM
      .MMM        MMMMMMMMMMM.           MMMM                    MMMMM
      MMM                .~MMMMMMM.      MMM.                  MMM   MMO
     MMM.                               MMMM                 MMMM     MM
    .MMM                                MMMM                MMM      IMM
    MMM                                DMMM               .MMM.      MM
   MMM                                 MMMM              MMMM       MM.
   MMM                                .MMM              MMM.       MM
  MMM                      MM        .MMM             MMM.       MMM.
 .MMM                     .MM  MM.   MMM~            MMM.      .MMM."""

def juste_un_doigt(oss=117):
    return"""_
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmdddhhhhhhhhhddddmdmmmmmmmmmmmmmmmmmmmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmddhyssoo+++//++++ssshhyo+o+++oossyyhddddmmmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMNNNNmmdhhysoo+/--.`````  -oshNd+.    `.--/osyyyyyhddmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho/:-.--:+smMMh////////hMMm///////////MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMNNNNmmmmmNmyo+/:-..``       .:/odms-`          `.:+yyhhhdmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+`    `.``  .NMMh:`    `:dMMd          `MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMNNNNmmddhdNMMdo::-..```         -./ho:`                `./hdNMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd`   -yNMMMMmhmMMMMMN    NMMMMd   .NNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMNNNmmddhyyhmMMmo:..```           `://o+:.                    -sdmmdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN`   +MMMMMMMMMMMMMMMN    NMMMMd   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMNNmmdhyss++hMMmy/-``          `.-/+oyhyso/:.`                .hs``-+hdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMy   `NMMNyyyyyyymMMMMN    NMMMMd   `oooooodMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMNNmdhyss+:-:omds:`           ``-/+syhmNNNmmdys+-.`              /o:`  -ohmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs   .MMMd       oMMMMN    NMMMMd          oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMNNmdhso+-.`..-.`            `.-/shmNMMMMMMMNNmmdyo/-`                  ``:smNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd    NMMNsss:   oMMMMN    NMMMMd   .ddddddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMNmdys+:.``.:o/..``         `.:ohNMMMMMMNNMMNNNNNmdhs/`                    `:hmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM-   :NMMMMMo   oMMMMN    NMMMMd   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMNNdhs+-`  .:os/-`          .-/odMMMMMMMMMMMMNNNNNNmmmhs/.                    .omNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN:   `/syys-   oMMNdo    sdNMMd   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNNmds+:::-``..`         ``.:+ymNMMMMMMMMMMMMMMNNmNmmmmmmho-`                 ` `/mMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNy:`         .sMMs`      `sMMd   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNmdy+/:/--`          `.-/+ohmMMMMMMMMMMMMMMMMNNNNmmmmmNNmho-`                    oNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyyyyhdmNMMMNddddddddNMMNdddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNmhs/-.`          ``-/+oydNMMMMMMMMMMMMMMMMMMMMNNmmmmNNNmdy+-.                 ` -dNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMNNdyo/-.`       `.:/+oshmNMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmNmdy+:.                 ` +NNNNNMMMMMMMMNsssmMMMMMMNhsssydMMMNdyssyhNMMMdysssymMMMMdsssMMMMMhsssMMNsssssymMMMyshMMMMMdssssyMMMMMMMMMMMMMMMM
            MMMMNmhs+:.``  ``.:oosyhdmNNMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmmmmdy+-`                  -mMMMMMMMNNNMM+ - -NMMMMo``/+/:+MMh-`-++::NMm:`./+/.`:mMMo ` sMMMm`` .MMd  /+/``oMM. /MMMMMmo  :hMMMMMMMMMMMMMMMM
            MMMMNmho/:.``:+oydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNNNNmmmmmmmdhs:.`               `+hy+sdNMMMNNNMh `m/ +MMMs  dMMMNMMm` oNMMMNMM- -NMMMN- -MM+ /``NMM: + .MMd  hMM: .MM. /MMMMMMN  sMMMMMMMMMMMMMMMMM
            MMMNNdyo/-..odmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMNNNNmmmmmNNmdyo:.              -dh+/+oymMMNNNm. +dh  hMM: .MMMMMMMy  dMMMMMMM  +MMMMM+  MM+ /y /Ms os .MMd  :/-`.yMM. /MMMMMMN  sMMMMMMMMMMMMMMMMM
            MMMNNdy+:-`:mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMNNNNNmmmNNNNNmdhs/.           `ohs++ssyymMMNN/ `---. .NMs  hMMMMMMm` +NMMMNMM- .mMMMm. -MM+ /M: y`-Ns .MMd  +yydNMMM. /MMMMMMN  sMMMMMMMMMMMMMMMMM
            MMMMNNd+:.`sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmmmmmmmNmmmdy/`         -ss++syyhhdNMNs  hNNNN. :MNo.`-//-+MMy-`-//:-MMm/``:/:``/mMM+ /Md   dMs .MMd  hMMMMMMM. .////hd+  :yMMMMMMMMMMMMMMMM
            MMMMNNm+:..mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMNmmmdddmmmmmNmdo-       `/oo/shdhhdmNMNysyMMMMMdyyNMMmdyyyhmMMMNdyyyhdMMMMmhyyyhmMMMMdyhMMhyhMMmyyMMNyymMMMMMMMyyyyyyymdyyyyhMMMMMMMMMMMMMMMM
            MMMNmdh+:.+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhssosyss++/+shhhhddddddddmNmmdy/.      ./+/+shdmhdNMNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMNNmhyo:.hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMds/:-.`       ```..--:/+osyhddmmdddds:`     ./--/sydmdmNNmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMNmhs+:.hMNMMMMMMMMMMMMMMMMMMMMMMMMMmhhsso+//:---:/++osssoo+/+++oyyhddddmmddhs:`    :o+/oydMmdNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMNmdyo/-sNNNNMMNMMMMMMMMMMMMMMMMMMMNmdmmddhsssosyyyyyyssooooosyysyyhhdmmmmmmmmho.   -sso+sdMdymMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMNNmdhs/:dmmNMNNMMMMMMMMMMMMMMMMMMMMMMMNmmhssooo/:/+/-..--..-/+osyhmmNNmmmmNmdhyo.  `+oo/yNmsyNMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNmmds-/hmmmNNNNMMMMMNNNNMMMMMMMMMMMMNmhso+++:-//./:`/syyhddhhdNMMMMMMNNNNNmdhs+--:+oo:sNmhmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNNNmd+./hddmNMMMdyo++sydmMMMMMMMMMMMNhsoo++/:++/hosymNNNmdddmNMMMMMMMMMMMNmmhsso+ooosoyMMNNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMNNNmmh:./hmmNMNo.``./ydmNNMMMMMMMMMMMdyssoo+ooomMMMMNNdhdNNMMMMMMMMMMMMMNNmdhssoooosssymmmmNdNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMNmdhy+-.:hdmm/`  ./yddddddddmMMMMMMMNhhdhyyhhNMMMNNmmNNMMMMMMMMMMMMMMMMMNmddysoooooosshNNNdhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMNNmdho-`:ydo   `:yhyssso+++shNMMMMMMNmmNNNmmMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhdhyossooossoyhyhhhNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMNNmh+-.-s+   :shy+:-:://osshNMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhhddhyssssoooos+osyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMNNds/-.--  -ymy/`-//+/+yhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhyyyhhyysssooo+oo+oossdMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMNmho+:.`` +mdo``.`.-`:hmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmddhhhyyyyyysssoo+++o+++oydmMMMMNMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMNmhysyy/. +dy/  .-:+hmNmNMMMMMMMMMMMNNNMMMMMMMNNddddhhhhhhyyssssyyyyhhyssyyyso++///+o++oyydNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMNmhyhNNh:/yy/ `+dmNMmhhNMMMMMMMMMMMNNNNNNNMMMMNyhddddhhyoo+++o+++shddhsosyysso+///+oo++osyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMNNmhdNMMNhsys-/mNNNdyhNMMMMMMMMMMMMMMMNNNNMMMMmyohmmdhhyssssyyssssdNMmssosysso+////+o++ossyhMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMNmdmNMMMMmyhhyddddhmMMMMMMMMMMMMMMMMMMNNNMMNs+/:shhhhhhhhyyysoooohNMNysosyyso/////+++oyssssmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMNmmNMMMMMhymmmddmNMMMMMMMMMMMMMMMMMMMMMNmd/.-:/oyhhhhddhhhyso/+oodMMhysossoo+////++//syssssyMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMNNNMMMMMMMhdNmNMMMMMMMMMMNmMMMMMMMMMMMNys/---/+ohdddmmmhso/:./yyhhNNdyo++ooo+////+o+/syyyyoNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMNNMMMMMMMMmNNMMMMMMMMMMNhyNMMMMMMMMNmhs+-..+oohmmNdho/:-.  -dmNNNmmds+//+o+////+oo+/syhysmMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMNMMMMMMMMMMNMMMMMMMMMMhssmNNmmmNNmhso+-` -syhmmyoos/ysoo`-dNNMMMNmdyo//+++////++++/syhhmMMMMMMMMMMNhydNMMNmNMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMmy+ohmmhhyyhysso///+yddyo+oodMmNNs:ohNmNMMMMMmho++ooo+++/+++++yydNMMMMMMMMMNdyoooydNMNNMMmyhhdmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhs+osdmmddmmmNNmmNNNmysyshMMMNNy:/yNNddNMMMMMmds++oso+/++++++syhMMMMMMMMMMNyossooooshmNMMmssyyhdddmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMNmho+oshmmmmNMMMMNmhyysomMMMMMN/hyymMMNhdNMMMMNmds++ooo+++//+++yyNMMMMMMMMMNysssssooooosydNMMNNNNNNdhhdNMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmdyo+oymNmmNMNdyso/ohNMMMMMMmdNdMMMMMMdhmMMMMMNdhs++oo++++////sdMMMMMMMMMMNysossyyssssooooymNMNMMMdyoosNMMNmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdhhhhsoshmmdmNh+. :NNMMMMMNdNNNMMMMMMMNdydNMMMMMNdhs++oo++////:/dMMMMMMMMMMMhsysysyyysssooo+oyhh+hNMMNmhshMMNyyhdmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyhhhdmNmdhh/.```hNddmNmNdMMMMMMMMMNhydNMMMMMNNdyo//++++/:/-:mMMMMMMMMMMMhyyyyysyyyysssssosyy+ymNMMMMMMMMNysoossyhdmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmNMMNdhmddhyyshydhMMMMMMMMMNmdhyymMMMMMMMNmds+/////:::-/mMMMMMMMMMMNhysyyyyyyyyyyyyyssyys/dMNNNNNMMMMMNMNmdhyyyyhdmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmNNNMMNNMMMMMNmmmNNMMMMMNNNmhhhmNMMMMMMMMMmdho/////::--oNMMMMMMMMMMNyyyyyyyyyyyyyyyyyyyhhosmNNmNMMMMMNNNMMMMMMMNmddhddmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmmmmmNMMMMMMMMMMMMMMMNNmdhhdmNMMMMMMMMMMMMmhs+/++:---:hMMMMMMMMMMMNyyysyyyyyyyyyyyyyyhhhy/mMNNMMMMMMMMMMMMMMMMMMMMMMNNmdddmmNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNmmmdddmNMMMMMMMNNNmddhdmMMMMMMMMMMMMMMMmyo+///:-.:sNMMMMMMMMMMMNyyyyyyysyyyyyyyyyyyhdh+sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmddmmmNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddhyyhmNNMMMMMMMMMMMMMMMMMMMMMMMMMMms+///:..-+mMMMMMMMMMMMMNhysyyyyyyyyyysyyyhhddmy:dNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmmdddmmmmNNNNNNNNNMMMMMMMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmdhyyyydmMMMMMMMMMMMMMMMMMMMMMNNmh+/://-`./hMMMMMMMMMMMMMNyssyyyyyyhyhyhhhhdddmmm:smmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhddddddmmmmmNNNNMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmddhyyyydmNMMMMMMMMMMMMMNNNmdhyo/:/+:.`:sNMMMMMMMMMMMMMNysssysyyyyhyhhhddddmmmmy:dddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhyyyyyyyhhhhdddMMMMMMMMMMMM
            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhyyyydmNMMMMMMMMNNdyo+oo+++oo+-`.omMMMMMMMMMMMMMMNyssssyysyyyyhhhdmmdddddh:hdhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmNNMMMMMMMNds+++oooossssMMMMMMMMMMMM
             """
